const BAD_REQUEST_ERROR_CODE = 400;
const UNAUTHORIZED = 401;
const NOT_FOUND_ERROR_CODE = 404;
const SERVER_ERROR_CODE = 500;

module.exports = {
  BAD_REQUEST_ERROR_CODE,
  UNAUTHORIZED,
  NOT_FOUND_ERROR_CODE,
  SERVER_ERROR_CODE,
};
